### ISSUE TITLE
Laminas\Filter v3 TODO

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-filter#177]
Work on v3 is in progress, this list is here to keep track of what's been done, and what needs to be done…

All refactored filters and components should come with entries in the migration guide and a companion patch documenting deprecations in the 2.x series where necessary.

- [x] `AbstractDateDropdown` - We should be able to remove this by refactoring inheritors #209 
- [x] `AbstractFilter` - Should be removed when possible
- [x] `AllowList` #151, #118
- [x] `BaseName` #148
- [x] `Boolean` #151, #149
- [x] `Callback` #152, #153
- [x] `Compress` and `Compress/*` #195 
- [x] `DataUnitFormatter` #155, #156
- [x] `DateSelect` #207
- [x] `DateTimeFormatter` #160
- [x] `DateTimeSelect` #209 
- [x] `Decompress` #195 
- [x] `DenyList` #174, #175, #176
- [x] `Digits` #161
- [x] `Dir` #216
- [x] `File\LowerCase` #154
- [x] `File\Rename` #222
- [x] `File\RenameUpload` #224, #223, #239 
- [x] `File\UpperCase` #154
- [x] `FilterChain` #208
- [x] `FilterPluginManager`
- [x] `FilterProviderInterface` - #204,#205
- [x] `ForceUriScheme`
- [x] `HtmlEntities` #215, #218
- [x] `Inflector` #220, #221
- [x] `MonthSelect` #200
- [x] `PregReplace` #178, #179
- [x] `RealPath` #198
- [x] `StringPrefix` #169, #170
- [x] `StringSuffix` #169, #170
- [x] `StringToLower` #154
- [x] `StringToUpper` #154
- [x] `StringTrim` #162, #163
- [x] `StripNewlines` #167
- [x] `StripTags` #214, #217
- [x] `ToFloat` #171
- [x] `ToInt` #171
- [x] `ToNull` #172, #173
- [x] `ToString` needs to apply recursively to arrays to be more useful + docs need updating #241
- [x] `UpperCaseWords` #154
- [x] `Word\AbstractSeparator` - We should be able to refactor inheritors to enable removal of this abstract class #194
- [x] `Word\CamelCaseToDash` #186
- [x] `Word\CamelCaseToSeparator` #186
- [x] `Word\CamelCaseToUnderscore` #186
- [x] `Word\DashToCamelCase` #194
- [x] `Word\DashToSeparator` #184 
- [x] `Word\DashToUnderscore` #193 
- [x] `Word\SeparatorToCamelCase` #194
- [x] `Word\SeparatorToDash` #193 
- [x] `Word\SeparatorToSeparator` #193 
- [x] `Word\UnderscoreToCamelCase` #194
- [x] `Word\UnderscoreToDash` #193 
- [x] `Word\UnderscoreToSeparator` #193 
- [x] `Word\UnderscoreToStudlyCase` #192

**Comment by gsteel** [comment]
Everything on the list is done ☑️
