### ISSUE TITLE
V3 Migration Guide TODO

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-filter#196]
This issue is for tracking content required in the migration guide for v2 -> v3

- [x] Removal of `AbstractFilter` - Document why, and provide refactoring examples
- [x] Final Everywhere, also tracked in #119
- [x] Addition of __invoke() to `FilterInterface` if not already covered
- [x] Removal of `AbstractSeparator` in #194 needs documenting as per `AbstractFilter`
- [x] Compress and Decompress refactor in #195 
- [x] Filter Chain Changes in #208 
- [x] Docs updates for `Rename` in #222 - Done in #233
